import Head from "next/head";
import { getDefaultProps } from "../../utils/defaultProps";
import { MessageLevels, MessageProps } from "../../components/Message";

export async function getStaticProps() {
  let p = getDefaultProps();
  p.navLinks.push({ href: "/", text: "home" });
  p.messages.push({ text: "test", level: MessageLevels.Err });

  return {
    props: p,
  };
}

export default function Page() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>private</main>
    </div>
  );
}
