import Head from "next/head";
import { getPrivateProps } from "../../lib/NextProps";
import { MessageLevels } from "../../components/Message";
import { GetServerSideProps } from "next/types";

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  let p = await getPrivateProps(ctx);
  if (p.private) {
    //private page
    return {
      props: p,
    };
  } else {
    //redirect to login
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }
};

export default function Page() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>private</main>
    </div>
  );
}
