import { GetStaticProps } from "next";
import Head from "next/head";
import { getDefaultPublicProps } from "../../utils/defaultProps";

export const getStaticProps: GetStaticProps = async () => {
  let p = getDefaultPublicProps();
  return {
    props: p,
  };
};

export default function Page() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>public</main>
    </div>
  );
}
